name: CI Makefile

on:
  push:
    branches: '*'
    pull_request:
      branches: '*'

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.12'
          - '5.22'
          - '5.32'
          - 'latest'
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}     # https://hub.docker.com/r/perldocker/perl-tester
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: cpanm --notest --installdeps .
      - name: perl Makefile.PL
        run: perl Makefile.PL
      - name: make
        run: make
      - name: Regular tests
        run: make test

  #Windows:
  #  runs-on: windows-latest

  #  steps:
  #    - uses: actions/checkout@v3
  #      with:
  #        submodules: recursive
  #    - name: perl -V
  #      run: perl -V
  #    - name: Install Dependencies
  #      run: cpanm --notest --installdeps .
  #    - name: perl Makefile.PL
  #      run: perl Makefile.PL
  #    - name: make
  #      run: make
  #    - name: Run Tests
  #      run: make test
